from student import Student
from course import Course
s1=Student("Jeje",20,"Freshaman")
s2=Student("AMY",10,"Sophmore")
# s1.courses.append("Math")
# s2.courses.append("English")
# print(s1.name)
# print(s2.name)
# print(Student.school)
# print(s1.school)
# print(s2.school)
# s1.enroll("MATH")
# print(s1.courses)
# s1.drop("MATH")
# print(s1.courses)
# s1.drop("English")

course1=Course("MATH",123,"AMY",4,2,0)
# course2=Course("English",124,"Jenny",3,1)
s1.enroll(course1)
print(s1.courses[0].name)
print(course1.students[0].name)
# print(course1.name)
# print(course1.students)
# print(course2.students)